# Generated by Django 5.1.6 on 2025-03-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thuoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_thuoc', models.CharField(max_length=255)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('so_luong', models.IntegerField()),
            ],
        ),
    ]
