# Generated by Django 5.1.6 on 2025-03-31 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_supplies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonThuoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_benh_nhan', models.CharField(max_length=255)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietDonThuoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('thuoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_supplies.thuoc')),
                ('don_thuoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='medical_supplies.donthuoc')),
            ],
        ),
    ]
