# Generated by Django 5.1.6 on 2025-03-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_supplies', '0002_donthuoc_chitietdonthuoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='donthuoc',
            name='ghi_chu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
